version: "3.9"
volumes:
  songs_data:  # Create a volume core_data that will contain the data for 'songs_persistence', such that when the container is stopped / crashes, the data remains.
  authentication_data:
  friends_data:
  playlists_data:
  activities_data:
services:
  activities_persistence:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
       - ./activities_persistence/:/docker-entrypoint-initdb.d
       - activities_data:/var/lib/postgresql/data
  songs_persistence:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres  # Can be any username & password combination, but we need to use the same combination in the code in 'songs'
      - POSTGRES_PASSWORD=postgres
    volumes:
      # Map the songs_persistence folder to the docker-entrypoint-initdb.d folder in the container.
      # This will ensure that the necessary files are present in the container for initializing the database(s)
      - ./songs_persistence/:/docker-entrypoint-initdb.d
      # Map the psql data from the container to a virtual volume, thus preserving the data after the container is stopped.
      - songs_data:/var/lib/postgresql/data
  authentication_persistence:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres  # Can be any username & password combination, but we need to use the same combination in the code in 'songs'
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./authentication_persistence/:/docker-entrypoint-initdb.d
      - authentication_data:/var/lib/postgresql/data
  friends_persistence:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./friends_persistence/:/docker-entrypoint-initdb.d
      - friends_data:/var/lib/postgresql/data
  playlists_persistence:
    image: docker.io/postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres  # Can be any username & password combination, but we need to use the same combination in the code in 'songs'
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./playlists_persistence/:/docker-entrypoint-initdb.d
      - playlists_data:/var/lib/postgresql/data
  activities:
    build: ./activities
    ports:
      - 5005:5000
    depends_on:
      activities_persistence
  playlists:
    build: ./playlists
    ports:
      - 5004:5000
    depends_on:
      playlists_persistence
  friends:
    build: ./friends
    ports:
      - 5003:5000
    depends_on:
      - friends_persistence
  authentication:
    build: ./authentication
    ports:
      - 5002:5000
    depends_on:
      - authentication_persistence
  songs:
    build: ./songs
    ports:
      - 5001:5000
    depends_on:
      - songs_persistence
  gui:
    build: ./gui
    ports:
      - 5000:5000